language: php

php: 
  - 5.3
  - 5.4

before_script: 
  - git clone --depth 1 git://github.com/ithinkihaveacat/zend-framework-1.11.9.git zend-framework

script: 
  - phpunit -c tests/phpunit.xml.dist tests/small
  - phpunit -c tests/phpunit.xml.dist tests/medium

notifications:
  email:
    - mjs@beebo.org
