language: php

php: 
  - 5.3
  - 5.4

branches:
  only:
    - master
    - composer

before_script: 
  - curl -s http://getcomposer.org/installer | php
  - php composer.phar install

script: 
  - phpunit -c tests/phpunit.xml.dist tests/small
  - phpunit -c tests/phpunit.xml.dist tests/medium

notifications:
  email:
    - mjs@beebo.org
